import type { ChatWorkspaceModel } from '../types'

const chatWorkspace: ChatWorkspaceModel = {
  brandName: 'WhisperLink',
  brandCaption: 'Visual chat workspace built for fast backend integration.',
  currentUser: {
    id: 'user-01',
    name: 'Adrian Munteanu',
    handle: '@adrian.ui',
    role: 'Product Designer',
    email: 'adrian@whisperlink.app',
    presence: 'online',
    avatarText: 'AM',
    accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
  },
  sideStats: [
    { id: 'stat-unread', label: 'Unread', value: '12' },
    { id: 'stat-online', label: 'Online', value: '18' },
    { id: 'stat-pending', label: 'Pending', value: '04' },
  ],
  actionButtons: [
    {
      id: 'search-user',
      label: 'Search User',
      note: 'Find any profile fast',
      tone: 'primary',
    },
    {
      id: 'profile-main',
      label: 'Profile',
      note: 'Main account card',
      tone: 'surface',
    },
    {
      id: 'friends',
      label: 'Friends',
      note: 'Active connections',
      tone: 'surface',
    },
    {
      id: 'add-friends',
      label: 'Add Friends',
      note: 'Invite new people',
      tone: 'surface',
    },
    {
      id: 'profile-preview',
      label: 'Profile',
      note: 'Public profile view',
      tone: 'surface',
    },
    {
      id: 'new-chat',
      label: 'New Chat',
      note: 'Create a fresh room',
      tone: 'primary',
    },
    {
      id: 'settings',
      label: 'Settings',
      note: 'Control the workspace',
      tone: 'surface',
    },
    {
      id: 'notifications',
      label: 'Notifications',
      note: 'Check unread alerts',
      tone: 'surface',
    },
  ],
  conversations: [
    {
      id: 'conv-01',
      section: 'Pinned',
      title: 'Mara Popa',
      message: 'I updated the hero visuals and left room for backend hooks.',
      time: '09:24',
      tag: 'Design',
      unreadCount: 3,
      avatarText: 'MP',
      accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      presence: 'online',
      pinned: true,
    },
    {
      id: 'conv-02',
      section: 'Pinned',
      title: 'Launch Crew',
      message: 'Need the final structure for chat, profile and notifications.',
      time: '08:56',
      tag: 'Team',
      unreadCount: 0,
      avatarText: 'LC',
      accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      presence: 'focus',
      pinned: true,
    },
    {
      id: 'conv-03',
      section: 'Recent',
      title: 'Sergiu Botezatu',
      message: 'Can you keep the class names simple for the API integration?',
      time: 'Yesterday',
      tag: 'Dev',
      unreadCount: 1,
      avatarText: 'SB',
      accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      presence: 'away',
    },
    {
      id: 'conv-04',
      section: 'Recent',
      title: 'QA Review',
      message: 'We only need frontend visuals for this version.',
      time: 'Yesterday',
      tag: 'QA',
      unreadCount: 0,
      avatarText: 'QR',
      accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      presence: 'online',
    },
    {
      id: 'conv-05',
      section: 'Groups',
      title: 'Friends Circle',
      message: 'Weekend meetup card can stay as a visual widget for now.',
      time: 'Monday',
      tag: 'Social',
      unreadCount: 5,
      avatarText: 'FC',
      accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      presence: 'online',
    },
  ],
  activeConversation: {
    id: 'conv-01',
    title: 'Mara Popa',
    subtitle: 'Senior UI Designer',
    topic: 'Landing room and chat handoff',
    statusLabel: 'Live review opened 12 minutes ago',
    participantCount: 4,
    participants: [
      {
        id: 'user-02',
        name: 'Mara Popa',
        handle: '@mara.design',
        role: 'Senior UI Designer',
        email: 'mara@whisperlink.app',
        presence: 'online',
        avatarText: 'MP',
        accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      },
      {
        id: 'user-03',
        name: 'Radu Toma',
        handle: '@radu.front',
        role: 'Frontend Engineer',
        email: 'radu@whisperlink.app',
        presence: 'focus',
        avatarText: 'RT',
        accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      },
      {
        id: 'user-04',
        name: 'Bianca Luca',
        handle: '@bianca.pm',
        role: 'Product Manager',
        email: 'bianca@whisperlink.app',
        presence: 'away',
        avatarText: 'BL',
        accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      },
      {
        id: 'user-01',
        name: 'Adrian Munteanu',
        handle: '@adrian.ui',
        role: 'Product Designer',
        email: 'adrian@whisperlink.app',
        presence: 'online',
        avatarText: 'AM',
        accent: 'linear-gradient(135deg, #8a2be2, #ff007f)',
      },
    ],
    highlights: [
      'Pure frontend layout, no backend logic',
      'Simple names for classes, ids and components',
      'Ready to split by API endpoints later',
    ],
    messages: [
      {
        id: 'msg-01',
        authorId: 'user-02',
        text: 'The new chat direction feels premium and different from Telegram.',
        time: '09:02',
        badge: 'Review',
      },
      {
        id: 'msg-02',
        authorId: 'user-01',
        text: 'Perfect. I kept the layout modular so the backend can connect later.',
        time: '09:06',
      },
      {
        id: 'msg-03',
        authorId: 'user-03',
        text: 'The left navigation is clean. The buttons can map directly to future endpoints.',
        time: '09:12',
      },
      {
        id: 'msg-04',
        authorId: 'user-01',
        text: 'Exactly. Search, friends, notifications and new chat already have isolated UI blocks.',
        time: '09:16',
        badge: 'Ready',
      },
    ],
    files: [
      { id: 'file-01', name: 'chat-page-wireframe.fig', meta: '2.4 MB  •  Design' },
      { id: 'file-02', name: 'frontend-structure.pdf', meta: '860 KB  •  Docs' },
      { id: 'file-03', name: 'api-map-notes.txt', meta: '12 KB  •  Notes' },
    ],
    insights: [
      {
        id: 'insight-01',
        title: 'Focused Mode',
        value: 'Visual Only',
        note: 'No live requests, no backend flows yet.',
      },
      {
        id: 'insight-02',
        title: 'Main Theme',
        value: 'Purple Pulse',
        note: 'Built around the requested gradient accent.',
      },
      {
        id: 'insight-03',
        title: 'Integration',
        value: 'Backend Ready',
        note: 'Clear slots for chats, friends, profile and alerts.',
      },
    ],
    composerHint: 'Write a message, attach a file or schedule a follow-up...',
  },
}

const chatService = {
  getChatWorkspace() {
    return chatWorkspace
  },
}

export default chatService
